version: "3.3"
services:
  sciquel-server:
    image: sciquel-server
    build: .
    ports:
      - 4000:4000
    environment:
      BASE_URL: http://localhost:4000/
      MONGO_URI: mongodb://backend-database
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - backend-networks
    depends_on:
      - backend-database
  
  backend-database:
    image: mongo:4
    networks:
      - backend-networks

networks:
  backend-networks: